### ISSUE TITLE
When using "Forced Original Position"; hangarmod load ignores position

### ISSUE THREAD

**Issue by kontu** [Casimir255/QuantumHangar#20]
When using "Forced Original Position"; hangarmod load ignores position

I saved a couple things to my hangar to test, tried to use hangarmod load to test forced position spawning while ignoring the cooldown - they spawned near my player instead of in the forced position they should have

Trying to do hm load from discord console breaks as well
`Exception has been thrown by the target of an invocation.`

https://i.imgur.com/XNBKXgr.png
low priority to me

**Comment by Casimir255** [comment]
You can now load grids from the console. They will force spawn where they were saved at.
