### ISSUE TITLE
moderator unhangar command spawning grids as unowned

### ISSUE THREAD

**Issue by GenWiggin** [Casimir255/QuantumHangar#24]
please set to command `!hangarmod load <username> <number>` to assign ownership of the grid to the player given in username. pasting in as owned by nobody results in grids shooting each other upon pasting, which is not conducive to grid recovery operations for staff teams.

**Comment by Casimir255** [comment]
Ahhhh. You guys are using the feature to transfer to the owner on load. Yeah this makes sense now

**Comment by Casimir255** [comment]
Issue has been fixed
