### ISSUE TITLE
Duplicate names with different case possibly overwrite each other

### ISSUE THREAD

**Issue by kontu** [Casimir255/QuantumHangar#27]
Player hangared "Production Facility"
Then later hangared "PRODUCTION FACILITY"
Both were in their hangar list; but only one SBC existed

Either one overwrote the other; or one never actually had the SBC saved
https://i.imgur.com/OeZi9PC.png

**Comment by Casimir255** [comment]
Freaking caps

**Comment by Casimir255** [comment]
Freaking windows and their case sensitive file saving. Should be fixed
