### ISSUE TITLE
feature request: Gps check before load

### ISSUE THREAD

**Issue by kontu** [Casimir255/QuantumHangar#33]
Players requesting a way to do like; `!hangar gps 1` to get the gps point 1 would load at if it has a forced position (just return "will spawn enar player, no forced gps" or something if it's not)

**Comment by Casimir255** [comment]
there is the !hangar load [ID] [bool SpawnNearPlayer]

this works if you have players choice on. Is this what you mean?

**Comment by kontu** [comment]
naw but this can be closed - the use case was leftover from when we migrated to QH and forceposition and many grids didn't have position saved to them; so some grids would load near the player. this was just a way for them to know which it would do

**Comment by Casimir255** [comment]
Coolio
