### ISSUE TITLE
Bug: HM Save not working

### ISSUE THREAD

**Issue by twistedgrim** [Casimir255/QuantumHangar#37]
When ingame on 3.1.02 running hm save while looking at a grid or hm save "gridname" dont seem to work at all.  

12:50:52.3412 [INFO]   Hangar.CommandSystem:  Running Admin command!
12:50:57.3418 [INFO]   Chat: Hangar (to TwistedGrim): Saved Failed!
12:50:57.3418 [INFO]   Torch.Commands.CommandManager: Player TwistedGrim ran command '!hm save "Twisted Solar Cluster Spawn"'

**Comment by Casimir255** [comment]
Fixed in latest update
