### ISSUE TITLE
[Bug] Wait time countdown doesn't seem to handle >1hr times

### ISSUE THREAD

**Issue by kontu** [Casimir255/QuantumHangar#43]
We have wait time set to 1200 minutes (20 hours); but in game it starts countdown at 1hr:
https://cdn.discordapp.com/attachments/744022608554492034/836268714591518820/2021-04-26_16_27_18-Space_Engineers.jpg

With the 1hr resetting each time you relog; until you get into the final hour

**Comment by Casimir255** [comment]
I blame @lumbyjack  and his time commit

**Comment by Casimir255** [comment]
(But i did fix it in latest commit)
