### ISSUE TITLE
[Feature Request] Loading Grids by their Name or ID, Instead of their List Number

### ISSUE THREAD

**Issue by voidvoidvoid** [Casimir255/QuantumHangar#65]
Hi there. I'd love to be able to load hangar grids by a static ID, rather than their order on the list. My reasoning for this is that I would be able to create hotkeys to load specific grids, or load a grid without having to refer to the list first. Something like "!hangar load BigShip", for example. This would be an awesome feature in order to make grid loading faster and more consistent.

**Comment by Casimir255** [comment]
Added in latest commit
